using System.Text;

namespace Augment.BindingGen;

sealed class CSharpEmitter : ILangEmitter
{
    public string Lang => "cs";
    public string FileName => "Bindings.g.cs";

    public string Generate(IReadOnlyList<Sym> symbols, string ns)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> AugmentBindingGen. Do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Augment;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        var byClass = new Dictionary<string, List<Sym>>();
        var order = new List<string>();
        foreach (var s in symbols)
        {
            var cls = s.IsMember && s.Class.Length > 0 ? Ident(s.Class) : "Global";
            if (!byClass.TryGetValue(cls, out var list)) { byClass[cls] = list = new(); order.Add(cls); }
            list.Add(s);
        }

        foreach (var cls in order)
        {
            sb.AppendLine($"public static unsafe class {cls}");
            sb.AppendLine("{");
            var seen = new HashSet<string>();
            foreach (var s in byClass[cls])
            {
                var name = Pascal(s.ShortName);
                if (!seen.Add(name)) continue;
                EmitMethod(sb, s, name);
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    static void EmitMethod(StringBuilder sb, Sym s, string name)
    {
        sb.AppendLine($"    public static class {name}");
        sb.AppendLine("    {");
        sb.AppendLine($"        public const string Symbol = \"{s.Symbol}\";");
        sb.AppendLine();
        sb.AppendLine("        public unsafe struct Ctx");
        sb.AppendLine("        {");
        sb.AppendLine("            private readonly AugmentCtx* _c;");
        sb.AppendLine("            public Ctx(AugmentCtx* c) { _c = c; }");
        if (s.IsMember)
            sb.AppendLine("            public nint Self => (nint)_c->Self;");
        sb.AppendLine("            public bool Cancelled { get => _c->Cancelled != 0; set => _c->Cancelled = (byte)(value ? 1 : 0); }");
        for (int i = 0; i < s.Params.Count; i++)
        {
            var p = s.Params[i];
            var pn = Esc(p.Name);
            if (p.Opaque)
                sb.AppendLine($"            public nint {pn} => (nint)_c->Args[{i}];");
            else
            {
                var ct = CsType(p.Type, false);
                sb.AppendLine($"            public {ct} {pn} {{ get => *({ct}*)_c->Args[{i}]; set => *({ct}*)_c->Args[{i}] = value; }}");
            }
        }
        if (!s.ReturnsVoid)
        {
            var rt = CsType(s.ReturnType, false);
            if (rt != "nint")
                sb.AppendLine($"            public {rt} Ret {{ get => *({rt}*)_c->Ret; set => *({rt}*)_c->Ret = value; }}");
        }
        sb.AppendLine("        }");
        sb.AppendLine();
        EmitPhase(sb, "Before",  "At.Head");
        EmitPhase(sb, "After",   "At.Return");
        EmitPhase(sb, "Replace", "At.Overwrite");
        EmitCall(sb, s);
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    static void EmitPhase(StringBuilder sb, string method, string at)
    {
        sb.AppendLine($"        public static void {method}(Action<Ctx> fn, int priority = 0, string? tag = null, string? id = null)");
        sb.AppendLine($"            => Mixin.Register(Symbol, {at}, c => fn(new Ctx(c)), priority, tag, id);");
    }

    static void EmitCall(StringBuilder sb, Sym s)
    {
        var pub = new List<string>();
        var sig = new List<string>();
        var args = new List<string>();
        if (s.IsMember) { pub.Add("nint self"); sig.Add("void*"); args.Add("(void*)self"); }
        foreach (var p in s.Params)
        {
            var nm = Esc(p.Name);
            if (p.Opaque) { pub.Add($"nint {nm}"); sig.Add("void*"); args.Add($"(void*){nm}"); }
            else { var ct = CsType(p.Type, false); pub.Add($"{ct} {nm}"); sig.Add(ct); args.Add(nm); }
        }
        string pubRet, prefix;
        if (s.ReturnsVoid) { pubRet = "void"; sig.Add("void"); prefix = ""; }
        else
        {
            var rt = CsType(s.ReturnType, false);
            if (rt == "nint") { pubRet = "nint"; sig.Add("void*"); prefix = "return (nint)"; }
            else { pubRet = rt; sig.Add(rt); prefix = "return "; }
        }
        sb.AppendLine();
        sb.AppendLine("        static nint _call;");
        sb.AppendLine($"        public static {pubRet} Call({string.Join(", ", pub)})");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_call == 0) _call = Mixin.Resolve(Symbol);");
        sb.AppendLine($"            {prefix}((delegate* unmanaged<{string.Join(", ", sig)}>)_call)({string.Join(", ", args)});");
        sb.AppendLine("        }");
    }

    static string CsType(string cpp, bool opaque)
    {
        if (opaque) return "nint";
        return cpp.Trim() switch
        {
            "void"                                          => "void",
            "bool"                                          => "byte",
            "char" or "s8" or "int8_t"                      => "sbyte",
            "u8" or "uint8_t" or "unsigned char"            => "byte",
            "s16" or "int16_t" or "short"                   => "short",
            "u16" or "uint16_t" or "unsigned short"         => "ushort",
            "s32" or "int32_t" or "int" or "BOOL"           => "int",
            "u32" or "uint32_t" or "unsigned int" or "uint" => "uint",
            "s64" or "int64_t" or "long long"               => "long",
            "u64" or "uint64_t" or "unsigned long long"     => "ulong",
            "f32" or "float"                                => "float",
            "f64" or "double"                               => "double",
            _                                               => "nint",
        };
    }

    static string Ident(string qualified)
    {
        var sb = new StringBuilder(qualified.Length);
        foreach (var c in qualified)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        var r = sb.ToString().Trim('_');
        return char.IsDigit(r[0]) ? "_" + r : r;
    }

    static string Pascal(string name)
    {
        var id = Ident(name);
        return id.Length > 0 ? char.ToUpperInvariant(id[0]) + id.Substring(1) : id;
    }

    static readonly HashSet<string> Keywords = new()
    {
        "base", "ref", "out", "in", "params", "object", "string", "int", "uint",
        "float", "double", "bool", "char", "byte", "sbyte", "short", "ushort",
        "long", "ulong", "void", "event", "lock", "class", "struct", "new", "this",
        "null", "true", "false", "return", "static", "const", "default", "operator",
    };

    static string Esc(string name)
    {
        var id = Ident(name);
        return Keywords.Contains(id) ? "@" + id : id;
    }
}
