# flake8: noqa: E501

#!/usr/bin/env python3
import json
import sys
import os
from dataclasses import dataclass, field
from typing import Protocol


@dataclass
class Param:
    name: str = ""
    type: str = ""
    is_pointer: bool = False
    is_ref: bool = False
    pointee_type: str = ""

    @property
    def opaque(self) -> bool:
        return self.is_pointer or self.is_ref

    @staticmethod
    def from_dict(d: dict) -> "Param":
        return Param(
            name=d.get("name", ""),
            type=d.get("type", ""),
            is_pointer=d.get("is_pointer", False),
            is_ref=d.get("is_ref", False),
            pointee_type=d.get("pointee_type", ""),
        )


@dataclass
class Sym:
    symbol: str = ""
    short_name: str = ""
    cls: str = ""
    namespace: str = ""
    is_member: bool = False
    return_type: str = ""
    returns_void: bool = False
    params: list[Param] = field(default_factory=list)

    @staticmethod
    def from_dict(d: dict) -> "Sym":
        return Sym(
            symbol=d.get("symbol", ""),
            short_name=d.get("short_name", ""),
            cls=d.get("class", ""),
            namespace=d.get("namespace", ""),
            is_member=d.get("is_member", False),
            return_type=d.get("return_type", ""),
            returns_void=d.get("returns_void", False),
            params=[Param.from_dict(p) for p in d.get("params", [])],
        )


class LangEmitter(Protocol):
    @property
    def lang(self) -> str: ...
    @property
    def file_name(self) -> str: ...
    def generate(self, symbols: list[Sym], ns: str) -> str: ...


class CSharpEmitter:
    lang = "cs"
    file_name = "Bindings.cs"

    def generate(self, symbols: list[Sym], ns: str) -> str:
        lines = [
            "// <auto-generated/>",
            f"namespace {ns};",
            "",
        ]
        for sym in symbols:
            params = ", ".join(
                f"{'nint' if p.opaque else p.type} {p.name}"
                for p in sym.params
            )
            ret = "void" if sym.returns_void else sym.return_type
            lines.append(f"// {sym.symbol}")
            lines.append(f"public static extern {ret} {sym.short_name}({params});")
            lines.append("")
        return "\n".join(lines)


EMITTERS: dict[str, LangEmitter] = {
    "cs": CSharpEmitter(),
}


def main(argv: list[str]) -> int:
    input_path = output_path = None
    lang = "cs"
    ns = "Game"

    args = iter(range(len(argv)))
    for i in args:
        match argv[i]:
            case "--in":        input_path  = argv[next(args)]
            case "--out":       output_path = argv[next(args)]
            case "--lang":      lang        = argv[next(args)]
            case "--namespace": ns          = argv[next(args)]
            case unknown:
                print(f"unknown arg: {unknown}", file=sys.stderr)
                return 2

    if input_path is None:
        print("usage: binding_gen.py --in symbols.json [--lang cs] [--out DIR]", file=sys.stderr)
        print(f"langs: {', '.join(EMITTERS)}", file=sys.stderr)
        return 2

    if lang not in EMITTERS:
        print(f"no emitter for '{lang}' (have: {', '.join(EMITTERS)})", file=sys.stderr)
        return 2

    emitter = EMITTERS[lang]
    with open(input_path) as f:
        data = json.load(f)
    symbols = [Sym.from_dict(s) for s in data.get("symbols", [])]

    src = emitter.generate(symbols, ns)

    if output_path is None:
        print(src, end="")
    else:
        path = os.path.join(output_path, emitter.file_name) if os.path.isdir(output_path) else output_path
        with open(path, "w") as f:
            f.write(src)
        print(f"wrote {len(symbols)} bindings -> {path}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))