# flake8: noqa: E501
from ..models import Sym

CS_KEYWORDS = {
    "base", "ref", "out", "in", "params", "object", "string", "int", "uint",
    "float", "double", "bool", "char", "byte", "sbyte", "short", "ushort",
    "long", "ulong", "void", "event", "lock", "class", "struct", "new", "this",
    "null", "true", "false", "return", "static", "const", "default", "operator",
}

CPP_TO_CS: dict[str, str] = {
    "void":                  "void",
    "bool":                  "byte",
    "char":                  "sbyte",  "s8":   "sbyte",   "int8_t":           "sbyte",
    "u8":                    "byte",   "uint8_t": "byte",  "unsigned char":    "byte",
    "s16":                   "short",  "int16_t": "short", "short":            "short",
    "u16":                   "ushort", "uint16_t": "ushort", "unsigned short": "ushort",
    "s32":                   "int",    "int32_t": "int",   "int":              "int",   "BOOL": "int",
    "u32":                   "uint",   "uint32_t": "uint", "unsigned int":     "uint",  "uint": "uint",
    "s64":                   "long",   "int64_t": "long",  "long long":        "long",
    "u64":                   "ulong",  "uint64_t": "ulong", "unsigned long long": "ulong",
    "f32":                   "float",  "float":   "float",
    "f64":                   "double", "double":  "double",
}


def _ident(qualified: str) -> str:
    r = "".join(c if c.isalnum() else "_" for c in qualified).strip("_")
    return "_" + r if r and r[0].isdigit() else r


def _pascal(name: str) -> str:
    i = _ident(name)
    return i[0].upper() + i[1:] if i else i


def _esc(name: str) -> str:
    i = _ident(name)
    return "@" + i if i in CS_KEYWORDS else i


def _type(cpp: str, opaque: bool = False) -> str:
    return "nint" if opaque else CPP_TO_CS.get(cpp.strip(), "nint")


class CSharpEmitter:
    lang = "cs"
    file_name = "Bindings.g.cs"

    def generate(self, symbols: list[Sym], ns: str) -> str:
        out: list[str] = []
        w = out.append
        w("// <auto-generated> AugmentBindingGen. Do not edit.")
        w("#nullable enable")
        w("using System;")
        w("using Augment;")
        w("")
        w(f"namespace {ns};")
        w("")

        by_class: dict[str, list[Sym]] = {}
        for s in symbols:
            cls = _ident(s.cls) if s.is_member and s.cls else "Global"
            by_class.setdefault(cls, []).append(s)

        for cls, syms in by_class.items():
            w(f"public static unsafe class {cls}")
            w("{")
            seen: set[str] = set()
            for s in syms:
                name = _pascal(s.short_name)
                if name in seen:
                    continue
                seen.add(name)
                self._emit_method(out, s, name)
            w("}")
            w("")

        return "\n".join(out) + "\n"

    def _emit_method(self, out: list[str], s: Sym, name: str) -> None:
        w = out.append
        w(f"    public static class {name}")
        w("    {")
        w(f'        public const string Symbol = "{s.symbol}";')
        w("")
        w("        public unsafe struct Ctx")
        w("        {")
        w("            private readonly AugmentCtx* _c;")
        w("            public Ctx(AugmentCtx* c) { _c = c; }")
        if s.is_member:
            w("            public nint Self => (nint)_c->Self;")
        w("            public bool Cancelled { get => _c->Cancelled != 0; set => _c->Cancelled = (byte)(value ? 1 : 0); }")
        for i, p in enumerate(s.params):
            pn = _esc(p.name)
            if p.opaque:
                w(f"            public nint {pn} => (nint)_c->Args[{i}];")
            else:
                ct = _type(p.type)
                w(f"            public {ct} {pn} {{ get => *({ct}*)_c->Args[{i}]; set => *({ct}*)_c->Args[{i}] = value; }}")
        if not s.returns_void:
            rt = _type(s.return_type)
            if rt != "nint":
                w(f"            public {rt} Ret {{ get => *({rt}*)_c->Ret; set => *({rt}*)_c->Ret = value; }}")
        w("        }")
        w("")
        self._emit_phase(out, "Before",  "At.Head")
        self._emit_phase(out, "After",   "At.Return")
        self._emit_phase(out, "Replace", "At.Overwrite")
        self._emit_call(out, s)
        w("    }")
        w("")

    def _emit_phase(self, out: list[str], method: str, at: str) -> None:
        out.append(f"        public static void {method}(Action<Ctx> fn, int priority = 0, string? tag = null, string? id = null)")
        out.append(f"            => Mixin.Register(Symbol, {at}, c => fn(new Ctx(c)), priority, tag, id);")

    def _emit_call(self, out: list[str], s: Sym) -> None:
        w = out.append
        pub, sig, args = [], [], []
        if s.is_member:
            pub.append("nint self"); sig.append("void*"); args.append("(void*)self")
        for p in s.params:
            nm = _esc(p.name)
            if p.opaque:
                pub.append(f"nint {nm}"); sig.append("void*"); args.append(f"(void*){nm}")
            else:
                ct = _type(p.type)
                pub.append(f"{ct} {nm}"); sig.append(ct); args.append(nm)
        if s.returns_void:
            pub_ret, prefix = "void", ""
            sig.append("void")
        else:
            rt = _type(s.return_type)
            if rt == "nint":
                pub_ret, prefix = "nint", "return (nint)"
                sig.append("void*")
            else:
                pub_ret, prefix = rt, "return "
                sig.append(rt)
        w("")
        w("        static nint _call;")
        w(f"        public static {pub_ret} Call({', '.join(pub)})")
        w("        {")
        w("            if (_call == 0) _call = Mixin.Resolve(Symbol);")
        w(f"            {prefix}((delegate* unmanaged<{', '.join(sig)}>)_call)({', '.join(args)});")
        w("        }")
