# flake8: noqa: E501
from ..models import StructDef


class LuauStructEmitter:
    lang = "luau"

    def generate(self, structs: list[StructDef], ns: str) -> dict[str, str]:
        """Returns {filename: source} for each struct."""
        return {
            f"Structs/{s.name}.luau": self._emit_struct(s)
            for s in structs
        }

    def _emit_struct(self, s: StructDef) -> str:
        out: list[str] = []
        w = out.append

        w(f"-- <auto-generated> AugmentBindingGen (structs). Do not edit.")
        w(f"")
        w(f'local Mixin = require("Augment.Mixin")')
        w(f"")
        w(f"local {s.name} = {{}}")
        w(f"")
        w(f"{s.name}.size = {s.size}")
        w(f"")
        w(f"{s.name}.fields = {{")
        seen: set[str] = set()
        for f in s.fields:
            if f.name in seen:
                continue
            seen.add(f.name)
            w(f'    ["{f.name}"] = {{ offset = {f.offset}, kind = "{f.kind}" }},')
        w(f"}}")
        w(f"")
        w(f"function {s.name}.view(self)")
        w(f"    return setmetatable({{}}, {{")
        w(f"        __index = function(_, k)")
        w(f"            local f = {s.name}.fields[k]")
        w(f"            if not f then error(\"{s.name} has no field '\" .. tostring(k) .. \"'\", 2) end")
        w(f"            return Mixin.read(self, f.offset, f.kind)")
        w(f"        end,")
        w(f"        __newindex = function(_, k, v)")
        w(f"            local f = {s.name}.fields[k]")
        w(f"            if not f then error(\"{s.name} has no field '\" .. tostring(k) .. \"'\", 2) end")
        w(f"            Mixin.write(self, f.offset, f.kind, v)")
        w(f"        end,")
        w(f"    }})")
        w(f"end")
        w(f"")
        w(f"return {s.name}")
        return "\n".join(out) + "\n"
