# flake8: noqa: E501
import re
from ..models import Sym
from .luau import CPP_TO_FFI

PREFIX_RE = re.compile(r"^[iobp]_(.+)$")


def _field_name(raw: str, idx: int) -> str:
    if not raw:
        return f"arg{idx}"
    m = PREFIX_RE.match(raw)
    return m.group(1) if m else raw


def _scalar_kind(p) -> str:
    if p.is_pointer or p.is_ref:
        return "ptr"
    return CPP_TO_FFI.get(p.type.strip(), "ptr")


def _flat(symbol: str) -> str:
    return symbol.replace("::", "_")


class LuauHookEmitter:
    lang = "luau"

    def generate(self, symbols: list[Sym], ns: str, structs: set) -> dict[str, str]:
        used: set[str] = set()
        specs: list[tuple] = []
        for s in symbols:
            fields: list[tuple[str, str]] = []
            if s.is_member and s.cls:
                if s.cls in structs:
                    used.add(s.cls)
                    fields.append(("self", f'{{ self = true, view = "{s.cls}" }}'))
                else:
                    fields.append(("self", "{ self = true }"))
            for i, p in enumerate(s.params):
                fname = _field_name(p.name, i)
                pointee = p.pointee_type.strip()
                if (p.is_pointer or p.is_ref) and pointee in structs:
                    used.add(pointee)
                    fields.append((fname, f'{{ index = {i}, view = "{pointee}" }}'))
                else:
                    fields.append((fname, f'{{ index = {i}, kind = "{_scalar_kind(p)}" }}'))
            specs.append((s.symbol, _flat(s.symbol), fields))
        return {"Hooks.luau": self._emit(specs, used)}

    def _emit(self, specs: list, used: set) -> str:
        out: list[str] = []
        w = out.append

        w("-- <auto-generated> AugmentBindingGen (hooks). Do not edit.")
        w("--!nocheck")
        w('local Mixin = require("Augment.Mixin")')
        w("")
        w("local Structs = {")
        for name in sorted(used):
            w(f'    {name} = require("CR.Structs.{name}"),')
        w("}")
        w("")
        w("local function makeCtx(spec, mctx)")
        w("    local cache = {}")
        w("    return setmetatable({}, {")
        w("        __index = function(_, k)")
        w("            if k == \"cancelled\" then return mctx.cancelled end")
        w("            local f = spec[k]")
        w("            if not f then error(\"hook ctx has no field '\" .. tostring(k) .. \"'\", 2) end")
        w("            if f.view then")
        w("                if cache[k] == nil then")
        w("                    local ptr = f.self and mctx.self or Mixin.arg(f.index, \"ptr\")")
        w("                    cache[k] = Structs[f.view].view(ptr)")
        w("                end")
        w("                return cache[k]")
        w("            elseif f.self then")
        w("                return mctx.self")
        w("            else")
        w("                return Mixin.arg(f.index, f.kind)")
        w("            end")
        w("        end,")
        w("        __newindex = function(_, k, v)")
        w("            local f = spec[k]")
        w("            if not f then error(\"hook ctx has no field '\" .. tostring(k) .. \"'\", 2) end")
        w("            if f.self or f.view then error(\"hook ctx field '\" .. k .. \"' is not writable\", 2) end")
        w("            Mixin.set_arg(f.index, f.kind, v)")
        w("        end,")
        w("    })")
        w("end")
        w("")
        w("local Hook = {}")
        w("")
        for symbol, flat, fields in specs:
            w(f"Hook.{flat} = function(fn, phase)")
            w("    local spec = {")
            for fname, spec_lua in fields:
                w(f"        {fname} = {spec_lua},")
            w("    }")
            w(f'    local b = Mixin.builder("{symbol}")')
            w("    local cb = function(mctx) fn(makeCtx(spec, mctx)) end")
            w('    if phase == "after" then b:after(cb) elseif phase == "replace" then b:replace(cb) else b:before(cb) end')
            w("    b:register()")
            w("end")
            w("")
        w("return Hook")
        return "\n".join(out) + "\n"
