# flake8: noqa: E501
from ..models import Sym

CPP_TO_LUAU: dict[str, str] = {
    "void":                 "nil",
    "bool":                 "boolean",
    "char":                 "number",   "s8":  "number",   "int8_t":             "number",
    "u8":                   "number",   "uint8_t": "number", "unsigned char":    "number",
    "s16":                  "number",   "int16_t": "number", "short":            "number",
    "u16":                  "number",   "uint16_t": "number", "unsigned short":  "number",
    "s32":                  "number",   "int32_t": "number", "int":              "number", "BOOL": "boolean",
    "u32":                  "number",   "uint32_t": "number", "unsigned int":    "number", "uint": "number",
    "s64":                  "number",   "int64_t": "number", "long long":        "number",
    "u64":                  "number",   "uint64_t": "number", "unsigned long long": "number",
    "f32":                  "number",   "float":   "number",
    "f64":                  "number",   "double":  "number",
}

LUAU_KEYWORDS = {
    "and", "break", "do", "else", "elseif", "end", "false", "for", "function",
    "if", "in", "local", "nil", "not", "or", "repeat", "return", "then",
    "true", "until", "while", "continue",
}


def _luau_type(cpp: str, opaque: bool = False) -> str:
    if opaque:
        return "number"
    return CPP_TO_LUAU.get(cpp.strip(), "number")


# cpp type -> ffi kind passed to Mixin.call for marshaling.
CPP_TO_FFI: dict[str, str] = {
    "bool": "u8", "char": "i8", "s8": "i8", "int8_t": "i8", "unsigned char": "u8",
    "u8": "u8", "uint8_t": "u8", "s16": "i16", "int16_t": "i16", "short": "i16",
    "u16": "u16", "uint16_t": "u16", "unsigned short": "u16",
    "s32": "i32", "int32_t": "i32", "int": "i32", "BOOL": "i32",
    "u32": "u32", "uint32_t": "u32", "unsigned int": "u32", "uint": "u32",
    "s64": "i64", "int64_t": "i64", "long long": "i64",
    "u64": "u64", "uint64_t": "u64", "unsigned long long": "u64",
    "f32": "f32", "float": "f32", "f64": "f64", "double": "f64",
}


def _ffi_kind(cpp: str, opaque: bool = False) -> str:
    if opaque:
        return "ptr"
    return CPP_TO_FFI.get(cpp.strip(), "ptr")


def _esc(name: str) -> str:
    return f"{name}_" if name in LUAU_KEYWORDS else name


def _pascal(name: str) -> str:
    return name[0].upper() + name[1:] if name else name


class LuauEmitter:
    lang = "luau"

    @property
    def file_name(self) -> str:
        return "Mixins.luau"  # placeholder; generate() writes per-class files

    def generate(self, symbols: list[Sym], ns: str) -> dict[str, str]:  # type: ignore[override]
        """Returns {filename: source} for each class."""
        by_class: dict[str, list[Sym]] = {}
        for s in symbols:
            cls = s.cls if s.is_member and s.cls else "Global"
            by_class.setdefault(cls, []).append(s)

        return {
            f"Mixins/{cls}.luau": self._emit_class(cls, syms)
            for cls, syms in by_class.items()
        }

    def _emit_class(self, cls: str, symbols: list[Sym]) -> str:
        out: list[str] = []
        w = out.append

        w(f"-- <auto-generated> AugmentBindingGen. Do not edit.")
        w(f"--!strict")
        w(f"")
        w(f"local Mixin = require(\"Augment.Mixin\")")
        w(f"")
        w(f"local {cls} = {{}}")
        w(f"")

        seen: set[str] = set()
        for s in symbols:
            name = _pascal(s.short_name)
            if name in seen:
                continue
            seen.add(name)
            self._emit_symbol(out, cls, s, name)

        w(f"return {cls}")
        return "\n".join(out) + "\n"

    def _emit_symbol(self, out: list[str], cls: str, s: Sym, name: str) -> None:
        w = out.append

        # --- Ctx type ---
        w(f"export type {name}Ctx = {{")
        if s.is_member:
            w(f"    self: number,")
        for p in s.params:
            pn = _esc(p.name)
            lt = _luau_type(p.type, p.opaque)
            w(f"    {pn}: {lt},")
        if not s.returns_void:
            rt = _luau_type(s.return_type)
            w(f"    ret: {rt}?,")
        w(f"    cancelled: boolean,")
        w(f"}}")
        w(f"")

        # --- Builder type ---
        w(f"type {name}Builder = {{")
        w(f"    before:   (self: {name}Builder, fn: ({name}Ctx) -> (), priority: number?, tag: string?, id: string?) -> {name}Builder,")
        w(f"    after:    (self: {name}Builder, fn: ({name}Ctx) -> (), priority: number?, tag: string?, id: string?) -> {name}Builder,")
        w(f"    replace:  (self: {name}Builder, fn: ({name}Ctx) -> (), priority: number?, tag: string?, id: string?) -> {name}Builder,")
        w(f"    register: (self: {name}Builder) -> (),")
        w(f"}}")
        w(f"")

        # --- Call signature ---
        call_params: list[str] = []
        arg_names: list[str] = []
        arg_kinds: list[str] = []
        if s.is_member:
            call_params.append("self: number")
            arg_names.append("self")
            arg_kinds.append('"ptr"')
        for p in s.params:
            pn = _esc(p.name)
            call_params.append(f"{pn}: {_luau_type(p.type, p.opaque)}")
            arg_names.append(pn)
            arg_kinds.append(f'"{_ffi_kind(p.type, p.opaque)}"')
        call_ret = "nil" if s.returns_void else _luau_type(s.return_type)

        # --- Symbol table ---
        w(f"{cls}.{name} = {{")
        w(f'    symbol = "{s.symbol}",')
        w(f"")

        # call()
        w(f"    call = function({', '.join(call_params)}): {call_ret}")
        w(f"        return Mixin.call(\"{s.symbol}\", {{ {', '.join(arg_kinds)} }}, {{ {', '.join(arg_names)} }})")
        w(f"    end,")
        w(f"")

        # mixin() -> Builder
        w(f"    mixin = function(): {name}Builder")
        w(f"        local builder = Mixin.builder(\"{s.symbol}\")")
        w(f"        return {{")
        for phase in ("before", "after", "replace"):
            w(f"            {phase} = function(self, fn, priority, tag, id)")
            w(f"                builder:{phase}(fn, priority, tag, id)")
            w(f"                return self")
            w(f"            end,")
        w(f"            register = function(self)")
        w(f"                builder:register()")
        w(f"            end,")
        w(f"        }}")
        w(f"    end,")
        w(f"}}")
        w(f"")